<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PredatorLite.Core\PredatorLite.Core.csproj" />
    <ProjectReference Include="..\PredatorLite.Platform.Windows\PredatorLite.Platform.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(PredatorLiteWindowsTargetFramework)</TargetFramework>
    <RuntimeIdentifier>$(PredatorLiteRuntimeIdentifier)</RuntimeIdentifier>
    <Platforms>$(PredatorLitePlatformTarget)</Platforms>
    <PlatformTarget>$(PredatorLitePlatformTarget)</PlatformTarget>
  </PropertyGroup>

</Project>
