<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PredatorLiteWindowsTargetFramework)</TargetFramework>
    <RuntimeIdentifier>$(PredatorLiteRuntimeIdentifier)</RuntimeIdentifier>
    <Platforms>$(PredatorLitePlatformTarget)</Platforms>
    <PlatformTarget>$(PredatorLitePlatformTarget)</PlatformTarget>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PredatorLite.Core\PredatorLite.Core.csproj" />
    <ProjectReference Include="..\..\src\PredatorLite.ElevatedHelper\PredatorLite.ElevatedHelper.csproj" />
    <ProjectReference Include="..\..\src\PredatorLite.FanGuard\PredatorLite.FanGuard.csproj" />
    <ProjectReference Include="..\..\src\PredatorLite.Platform.Windows\PredatorLite.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
