<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PredatorLite.Core\PredatorLite.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>$(PredatorLiteWindowsTargetFramework)</TargetFramework>
  </PropertyGroup>

</Project>
